# Generated by Django 5.2.3 on 2025-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0017_alter_salsa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre de la bebida', max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pancho',
            name='nombre',
            field=models.CharField(help_text='Nombre del pancho', max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pancho',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio expresado en pesos', max_digits=15, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='salsa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la salsa', null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='salsa',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre de la salsa', max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(blank=True, help_text='Calle de la sucursal', max_length=120, null=True, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal', max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nroCalle',
            field=models.BigIntegerField(blank=True, help_text='Nro. de la calle', null=True, verbose_name='nroCalle'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='piso',
            field=models.BigIntegerField(blank=True, help_text='Nro. de piso', null=True, verbose_name='piso'),
        ),
    ]
