# Generated by Django 5.2.3 on 2025-06-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0018_alter_sucursal_options_alter_bebida_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallebebidaventa',
            options={'verbose_name': 'Detalle de la venta de Bebida', 'verbose_name_plural': 'Detalles de la venta de Bebida'},
        ),
        migrations.AlterModelOptions(
            name='detallepanchoventa',
            options={'verbose_name': 'Detalle de la venta de Pancho', 'verbose_name_plural': 'Detalles de la venta de Pancho'},
        ),
    ]
